"""Add PKCE verifier column

Revision ID: 7648cf5586b8
Revises: b610e434963d
Create Date: 2026-04-07 08:46:25.859034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7648cf5586b8'
down_revision: Union[str, Sequence[str], None] = 'b610e434963d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('pkce_verifier', sa.String(), nullable=True, comment='Temporary storage for OAuth PKCE handshake'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_tokens', 'pkce_verifier')
    # ### end Alembic commands ###
